CREATE TABLE `newsletter_playbook_interactions` (
	`id` text PRIMARY KEY NOT NULL,
	`subscriber_id` text,
	`playbook_id` text,
	`interaction_type` text NOT NULL,
	`platform` text,
	`article_slug` text,
	`email_campaign_id` text,
	`metadata` text DEFAULT '{}',
	`created_at` integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (`subscriber_id`) REFERENCES `newsletter_subscribers`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`playbook_id`) REFERENCES `playbooks`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `playbook_analytics` (
	`id` text PRIMARY KEY NOT NULL,
	`playbook_id` text,
	`event_type` text NOT NULL,
	`platform` text,
	`user_id` text,
	`session_id` text,
	`visitor_id` text,
	`referrer_url` text,
	`utm_source` text,
	`utm_medium` text,
	`utm_campaign` text,
	`article_slug` text,
	`country_code` text,
	`device_type` text,
	`user_agent` text,
	`ip_address` text,
	`revenue_cents` integer DEFAULT 0,
	`currency` text DEFAULT 'USD',
	`external_transaction_id` text,
	`metadata` text DEFAULT '{}',
	`created_at` integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (`playbook_id`) REFERENCES `playbooks`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `playbook_experiments` (
	`id` text PRIMARY KEY NOT NULL,
	`playbook_id` text,
	`name` text NOT NULL,
	`description` text,
	`hypothesis` text,
	`experiment_type` text NOT NULL,
	`status` text DEFAULT 'draft',
	`traffic_percent` integer DEFAULT 50,
	`control_config` text DEFAULT '{}',
	`variant_config` text DEFAULT '{}',
	`primary_metric` text DEFAULT 'conversion_rate',
	`control_views` integer DEFAULT 0,
	`control_conversions` integer DEFAULT 0,
	`variant_views` integer DEFAULT 0,
	`variant_conversions` integer DEFAULT 0,
	`confidence_level` real DEFAULT 0.95,
	`is_significant` integer DEFAULT false,
	`winner` text,
	`start_date` integer,
	`end_date` integer,
	`created_at` integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` integer DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (`playbook_id`) REFERENCES `playbooks`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `playbook_platforms` (
	`id` text PRIMARY KEY NOT NULL,
	`playbook_id` text NOT NULL,
	`platform` text NOT NULL,
	`external_product_id` text NOT NULL,
	`external_price_id` text,
	`price_cents` integer NOT NULL,
	`currency` text DEFAULT 'USD',
	`checkout_url` text,
	`platform_config` text DEFAULT '{}',
	`is_active` integer DEFAULT true,
	`sync_status` text DEFAULT 'synced',
	`last_synced_at` integer,
	`sync_error` text,
	`created_at` integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` integer DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (`playbook_id`) REFERENCES `playbooks`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `playbook_platforms_playbook_id_platform_unique` ON `playbook_platforms` (`playbook_id`,`platform`);--> statement-breakpoint
CREATE TABLE `playbook_purchases` (
	`id` text PRIMARY KEY NOT NULL,
	`playbook_id` text,
	`customer_email` text,
	`platform` text NOT NULL,
	`external_transaction_id` text NOT NULL,
	`external_customer_id` text,
	`amount_cents` integer NOT NULL,
	`currency` text DEFAULT 'USD',
	`platform_fee_cents` integer DEFAULT 0,
	`net_revenue_cents` integer NOT NULL,
	`referrer_url` text,
	`utm_source` text,
	`utm_medium` text,
	`utm_campaign` text,
	`article_slug` text,
	`time_from_first_view_hours` integer,
	`status` text DEFAULT 'completed',
	`refund_reason` text,
	`refunded_at` integer,
	`refund_amount_cents` integer DEFAULT 0,
	`is_first_purchase` integer DEFAULT true,
	`customer_ltv_cents` integer DEFAULT 0,
	`download_count` integer DEFAULT 0,
	`first_download_at` integer,
	`last_download_at` integer,
	`created_at` integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` integer DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (`playbook_id`) REFERENCES `playbooks`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `playbook_purchases_platform_external_transaction_id_unique` ON `playbook_purchases` (`platform`,`external_transaction_id`);--> statement-breakpoint
CREATE TABLE `playbook_testimonials` (
	`id` text PRIMARY KEY NOT NULL,
	`playbook_id` text,
	`customer_email` text,
	`customer_name` text,
	`customer_title` text,
	`rating` integer,
	`title` text,
	`content` text NOT NULL,
	`time_to_value_days` integer,
	`results_achieved` text,
	`is_verified` integer DEFAULT false,
	`is_featured` integer DEFAULT false,
	`photo_url` text,
	`purchase_platform` text,
	`purchase_date` integer,
	`status` text DEFAULT 'pending',
	`moderated_by` text,
	`moderated_at` integer,
	`created_at` integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` integer DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (`playbook_id`) REFERENCES `playbooks`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `playbook_versions` (
	`id` text PRIMARY KEY NOT NULL,
	`playbook_id` text,
	`version` text NOT NULL,
	`version_type` text DEFAULT 'minor',
	`title` text NOT NULL,
	`headline` text NOT NULL,
	`short_description` text NOT NULL,
	`long_description` text,
	`feature_bullets` text DEFAULT '[]',
	`base_price_cents` integer NOT NULL,
	`change_summary` text,
	`changed_by` text,
	`views_this_version` integer DEFAULT 0,
	`conversions_this_version` integer DEFAULT 0,
	`revenue_this_version_cents` integer DEFAULT 0,
	`created_at` integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (`playbook_id`) REFERENCES `playbooks`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `playbooks` (
	`id` text PRIMARY KEY NOT NULL,
	`sku` text NOT NULL,
	`slug` text NOT NULL,
	`title` text NOT NULL,
	`headline` text NOT NULL,
	`short_description` text NOT NULL,
	`long_description` text,
	`feature_bullets` text DEFAULT '[]',
	`cover_image_url` text,
	`cover_image_alt` text,
	`gallery_images` text DEFAULT '[]',
	`demo_video_url` text,
	`base_price_cents` integer NOT NULL,
	`currency` text DEFAULT 'USD',
	`pricing_strategy` text DEFAULT 'fixed',
	`stripe_product_id` text,
	`stripe_price_id` text,
	`lemonsqueezy_product_id` text,
	`lemonsqueezy_variant_id` text,
	`gumroad_product_id` text,
	`status` text DEFAULT 'draft',
	`category` text,
	`tags` text DEFAULT '[]',
	`difficulty_level` text DEFAULT 'beginner',
	`meta_title` text,
	`meta_description` text,
	`featured_testimonial_id` text,
	`is_featured` integer DEFAULT false,
	`launch_date` integer,
	`total_views` integer DEFAULT 0,
	`total_purchases` integer DEFAULT 0,
	`conversion_rate` real DEFAULT 0,
	`total_revenue_cents` integer DEFAULT 0,
	`version` text DEFAULT '1.0',
	`changelog` text,
	`created_at` integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` integer DEFAULT CURRENT_TIMESTAMP,
	`published_at` integer,
	`deleted_at` integer,
	`search_content` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `playbooks_sku_unique` ON `playbooks` (`sku`);--> statement-breakpoint
CREATE UNIQUE INDEX `playbooks_slug_unique` ON `playbooks` (`slug`);